### ISSUE TITLE
Not able to reproduce results

### ISSUE THREAD

**Issue by mattposka** [bcmi/GracoNet-Object-Placement#10]
The graconet model does not converge when training on the OPA dataset. I am following the training directions described, but I am not able to reproduce the baseline results. After one epoch of training the FID is ~41 and after 11 epochs of training the FID is ~71. 

Both Placenet and Terse seem to be working as expected, but the graconet model doesn't converge. Is anyone else able to reproduce the baseline results? Are there different parameters I should use, or is there something else wrong with the code? Thanks!

**Comment by ustcnewly** [comment]
The adversarial loss may increase the training difficulty, you can try replacing adversarial loss with classification loss (using fixed SOPA as binary classification model). Additionally, I recommend FOPA https://github.com/bcmi/FOPA-Fast-Object-Placement-Assessment, which is more stable and effective.
