### ISSUE TITLE
About application

### ISSUE THREAD

**Issue by David-19940718** [bcmi/GracoNet-Object-Placement#2]
您好，很有意思的工作。请教下一个问题，目前我有一个需求，就是想将多张目标截图随机黏贴到一张背景图上，类似于copy-paste的功能，但有一个问题就是黏贴后的合成图像感觉很不真实，偶然之间看到还有这个方向，请问这个模型是否可以实现类似的功能，比如我提供一张扣出来的图（不一定是pixel-level的），还有一张背景图，是否能直接生成？

**Comment by ustcnewly** [comment]
你好，图像合成是个很复杂的任务，包括很多子任务，可以看一下https://github.com/bcmi/Awesome-Image-Composition, 根据要实现的功能找到对应的子任务。
