### ISSUE TITLE
训练时这样的情况是否是收敛的

### ISSUE THREAD

**Issue by lzclzclzc12** [bcmi/GracoNet-Object-Placement#4]
[Epoch 11/11] [Batch 3811/3880] [G - gan1: 6.830, gan2: 6.101, rec: 0.151, kld: 0.0976] [D - real: 0.428, fake1: 0.016, fake2: 0.023]
[Epoch 11/11] [Batch 3821/3880] [G - gan1: 6.830, gan2: 6.102, rec: 0.151, kld: 0.0978] [D - real: 0.428, fake1: 0.016, fake2: 0.023]
[Epoch 11/11] [Batch 3831/3880] [G - gan1: 6.833, gan2: 6.104, rec: 0.151, kld: 0.0980] [D - real: 0.428, fake1: 0.016, fake2: 0.023]
[Epoch 11/11] [Batch 3841/3880] [G - gan1: 6.835, gan2: 6.107, rec: 0.151, kld: 0.0982] [D - real: 0.428, fake1: 0.016, fake2: 0.023]
[Epoch 11/11] [Batch 3851/3880] [G - gan1: 6.838, gan2: 6.110, rec: 0.151, kld: 0.0984] [D - real: 0.428, fake1: 0.016, fake2: 0.023]
[Epoch 11/11] [Batch 3861/3880] [G - gan1: 6.839, gan2: 6.114, rec: 0.151, kld: 0.0986] [D - real: 0.428, fake1: 0.016, fake2: 0.022][Epoch 11/11] [Batch 3871/3880] [G - gan1: **6.840**, gan2: **6.116**, rec: 0.151, kld: 0.0988] [D - real: 0.428, fake1: 0.016, fake2: 0.022]

**Comment by Siyuan-Zhou** [comment]
@lzclzclzc12 The training losses might increase in some periods and decrease in other periods, which can not precisely reflect the training quality. We suggest using evaluation results for a more straightforward reflection.
