### ISSUE TITLE
Failed to infer with eval_type 'sample'

### ISSUE THREAD

**Issue by Saumya-svm** [bcmi/GracoNet-Object-Placement#8]
Hi,
I tried to perform inference with eval_type = 'sample', but was facing issue with it. I was getting the following ValueError - 
`ValueError: not enough values to unpack (expected 18, got 11)`

The code that I ran for inference is -
`python infer.py --data_root new_OPA --expid graconet --epoch 11 --eval_type sample `

Kindly suggest what might have caused this error. I have performed the preprocessing step as well.

**Comment by Siyuan-Zhou** [comment]
@Saumya-svm Hi, the current code only support "--eval_type sample" in "main.py" ( https://github.com/bcmi/GracoNet-Object-Placement/blob/713d6df5a41c738e2a5edf5db98b315046855b76/main.py#L94 ). Please use "--eval_type eval" or "--eval_type evaluni" in "infer.py".
