### ISSUE TITLE
您好，我得到的FID和论文的不一样，我想知道我的实验设计是哪里出了错误，希望作者能帮助我一下，谢谢。

### ISSUE THREAD

**Issue by 1621031303** [bcmi/GracoNet-Object-Placement#9]
我使用作者您github里提供的代码和checkpoints，按照论文里描述的实验设置，运行的是您github里给的这条命令：
![)0X8 0(C@X2QYP N1%10X9](https://user-images.githubusercontent.com/45231898/215369727-be025d5a-4526-4fff-8882-0753e83f8fff.png)
然后得到9640张合成的图像。
然后我求FID，这里的真值使用的也是按照论文的描述，是OPA的test集的正样本（3588张组合图像）
最后得到的FID值如下：
![3XE45`BLV{$(A7S6{) MYUF](https://user-images.githubusercontent.com/45231898/215370010-28363fef-a2cb-48d7-ab2d-5ccfd8e35924.png)
（求FID时按照论文和代码里的描述，把合成图像和真值图像都resize成299*299）
但是论文里FID是这样的：
![image](https://user-images.githubusercontent.com/45231898/215370207-c7a60d5b-d56a-4cae-aa00-5e17ba533da0.png)
我想肯定是我的实验设置有不对的地方，希望您能指点我一下，感激不尽。

**Comment by Siyuan-Zhou** [comment]
@1621031303 如果您是完全按照README中的实验设置，使用eval_fid.sh来求FID的话，应该不会有这么大的偏差。我建议您按照README中的流程重新跑若干次infer和eval，因为生成合成图的过程带有一定的随机性，取多次的结果取平均会得到更接近期望值的结果。
